{
    'name': 'Product Inventory',
    'version': '19.0.1.0.0',
    'category': 'Management',
    'summary': 'Product Inventory',
    'author': 'Nhan',
    'license': 'AGPL-3',
    'depends': ['base', 'product', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'views/product_list.xml',
        'views/bom_views.xml',
        'views/work_order.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'sequence': -1,
}