{
    'name': 'Product Inventory',
    'version': '19.0.1.0.2',
    'category': 'Management',
    'summary': 'Product Inventory',
    'author': 'Nhan',
    'license': 'AGPL-3',
    'depends': ['sale_management', 'mrp', 'stock', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/production_wizard_view.xml',
        'views/production_order_views.xml',
        'views/bom_views.xml',
        'views/product_views.xml',
        'views/mrp_planner_menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'sequence': -1,
}